[package]
name          = "goboscript"
description   = "goboscript is the Scratch compiler."
version       = "0.1.0"
license       = "MIT"
keywords      = ["scratch", "compiler"]
categories    = ["compilers"]
documentation = "https://aspizu.github.io/goboscript"
homepage      = "https://github.com/aspizu/goboscript"
repository    = "https://github.com/aspizu/goboscript"
edition       = "2021"
exclude       = ["/tools"]

[dependencies]
clap          = "4.5.2"
clap_complete_command = "0.5.1"
clap_derive   = "4.5.0"
colored       = "2.1.0"
crc32fast     = "1.4.0"
fuzzy-matcher = "0.3.7"
lalrpop-util  = "0.20.2"
logos         = "0.14.0"
md-5          = "0.10.6"
serde_json    = "1.0.114"
strum         = { version = "0.26.1", features = ["derive"] }
strum_macros  = "0.26.1"

[build-dependencies]
lalrpop = "0.20.2"
