[package]
name    = "goboscript"
version = "0.1.0"
edition = "2021"

[dependencies]
clap          = "4.5.2"
clap_derive   = "4.5.0"
colored       = "2.1.0"
crc32fast     = "1.4.0"
fuzzy-matcher = "0.3.7"
lalrpop-util  = "0.20.2"
logos         = "0.14.0"
md-5          = "0.10.6"
serde_json    = "1.0.114"
strum         = { version = "0.26.1", features = ["derive"] }
strum_macros  = "0.26.1"

[build-dependencies]
lalrpop = "0.20.2"
